jenkins:
  numExecutors: 0
  clouds:
  - kubernetes:
      name: 'kubernetes'
      containerCapStr: "10"
      skipTlsVerify: true
      namespace: "ci"
      jenkinsUrl: "http://jenkins-master.ci.svc.cluster.local"
      maxRequestsPerHostStr: "32"
      name: "kubernetes"
      templates:
      - hostNetwork: false
        name: "mavenTemplate"
        namespace: "ci"
        yaml: |-
          apiVersion: v1
          kind: Pod
          spec:
            containers:
              - name: maven
                image: maven:3.3.9-jdk-8-alpine
                command: ['cat']
                tty: true
                volumeMounts:
                  - mountPath: /root/.m2/repository
                    name: maven-cache-storage
            volumes:
                - name: maven-cache-storage
                  persistentVolumeClaim:
                    claimName: maven-cache-pv-claim
        yamlMergeStrategy: "override"
jobs:
  - script: >
      for(it in ['constellation-common']) {
          /*why am i concatenating strings like that? because the plugin is replacing the variables before processing the groovy script, so i'm unable to just use string interpolation pos*/
          def repoURL = 'https://github.com/FeldmannJR/'
          repoURL = repoURL.concat(it)
          repoURL = repoURL.concat('.git');
          pipelineJob(it) {
              definition {
                  cpsScm {
                      scriptPath 'Jenkinsfile'
                      scm {
                        git {
                            remote { url repoURL }
                            branch '*/master'
                            extensions {}
                        }
                      }
                  }
              }
          }
      }
