credentials:
  system:
    domainCredentials:
    - credentials:
      - usernamePassword:
          id: "repository-credential"
          password: "${DEPLOYER_PASSWORD}"
          scope: GLOBAL
          username: "jenkins-deployer"
jenkins:
  numExecutors: 0
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "${JENKINS_ADMIN_PASSWORD}"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  clouds:
  - kubernetes:
      name: 'kubernetes'
      containerCapStr: "10"
      skipTlsVerify: true
      namespace: "ci"
      jenkinsUrl: "http://jenkins-master.ci.svc.cluster.local"
      maxRequestsPerHostStr: "32"
      name: "kubernetes"
      templates:
      - hostNetwork: false
        name: "mavenTemplate"
        namespace: "ci"
        yaml: |-
          apiVersion: v1
          kind: Pod
          spec:
            containers:
              - name: maven
                image: maven:3.3.9-jdk-8-alpine
                command: ['cat']
                tty: true
                volumeMounts:
                  - mountPath: /root/.m2/repository
                    name: maven-cache-storage
            volumes:
                - name: maven-cache-storage
                  persistentVolumeClaim:
                    claimName: maven-cache-pv-claim
        yamlMergeStrategy: "override"
unclassified:
  location:
    adminAddress: "feldmannjunior@gmail.com"
    url: "http://jenkins.minikube/"
  globalConfigFiles:
    configs:
    - globalMavenSettings:
        comment: "Global settings"
        content: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\n<settings xmlns=\"\
          http://maven.apache.org/SETTINGS/1.0.0\" \n          xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\
          \ \n          xsi:schemaLocation=\"http://maven.apache.org/SETTINGS/1.0.0\
          \ http://maven.apache.org/xsd/settings-1.0.0.xsd\">\n\n</settings>\n"
        id: "maven-settings"
        isReplaceAll: true
        name: "Global MavenSettings"
        providerId: "org.jenkinsci.plugins.configfiles.maven.GlobalMavenSettingsConfig"
        serverCredentialMappings:
        - credentialsId: "repository-credential"
          serverId: "constellation-repository"
tool:
  maven:
    globalSettingsProvider:
      mvn: 
        settingsConfigId: "maven-settings"
# Creating jobs
jobs:
  - script: >
      for(it in ['constellation-common']) {
          /*why am i concatenating strings like that? because the plugin is replacing the variables before processing the groovy script, so i'm unable to just use string interpolation pos*/
          def repoURL = 'https://github.com/FeldmannJR/'
          repoURL = repoURL.concat(it)
          repoURL = repoURL.concat('.git');
          pipelineJob(it) {
              definition {
                  cpsScm {
                      scriptPath 'Jenkinsfile'
                      scm {
                        git {
                            remote { url repoURL }
                            branch '*/master'
                            extensions {}
                        }
                      }
                  }
              }
          }
      }