apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pv-claim
  labels:
    app: jenkins
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  selector:
    matchLabels:
      app: jenkins
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-master
  template:
    metadata:
      labels:
        app: jenkins-master
    spec:
      containers:
      - name: jenkins
        image: constellation/jenkins-master:1.0
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
          - name: JAVA_OPTS
            value: -Djenkins.install.runSetupWizard=false
        ports:
          - name: http-port
            containerPort: 8080
          - name: jnlt-port
            containerPort: 50000
        volumeMounts:
          - mountPath: /var/jenkins_home 
            name: jenkins-storage
      securityContext:
        fsGroup: 1000
      volumes:
        - name: jenkins-storage
          persistentVolumeClaim:
            claimName: jenkins-pv-claim

--- 
apiVersion: v1
kind: Service
metadata:
  name: jenkins-master
spec:
  type: ClusterIP
  selector:
    app: jenkins-master
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: jnlp
    port: 50000
    targetPort: 50000
--- 
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: jenkins-ingress
spec:
  rules:
    - host: jenkins.minikube
      http:
        paths:
          - path: /
            backend:
              serviceName: jenkins-master       
              servicePort: 8080