apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maven-cache-pv-claim
  namespace: jenkins
  labels:
    app: jenkins
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi