apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: localhost:5000/constellation/mariadb
        imagePullPolicy: IfNotPresent
        resources:
            limits:
              memory: "256Mi"
              cpu: "1"  
        ports:
        - containerPort: 3306
          name: mariadb-port
        env:
          - name: MARIADB_ROOT_PASSWORD
            valueFrom:
                secretKeyRef:
                  name: mariadb-secrets
                  key: password
        volumeMounts:
          - mountPath: /bitnami/mariadb 
            name: mariadb-storage
      securityContext:
        fsGroup: 1001
      volumes:
        - name: mariadb-storage
          persistentVolumeClaim:
            claimName: mariadb-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
spec:
  type: ClusterIP
  selector:
    app: mariadb
  ports:
  - name: mariadb-port
    port: 3306
---