apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  selector:
    app: mariadb
  ports:
  - port: 3306
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pv-claim
  labels:
    app: mariadb
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  selector:
    matchLabels:
      app: mariadb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: constellation/mariadb:1.0
        ports:
        - containerPort: 3306
          name: mariadb
        env:
          - name: MARIADB_ROOT_PASSWORD
            valueFrom:
                secretKeyRef:
                  name: mariadb-pass
                  key: password
        volumeMounts:
          - mountPath: /bitnami/mariadb 
            name: mariadb-storage
      securityContext:
        fsGroup: 1001
      volumes:
        - name: mariadb-storage
          persistentVolumeClaim:
            claimName: mariadb-pv-claim
