apiVersion: v1
kind: PersistentVolume
metadata: 
  name: mariadb-pv
  labels:
    type: local
    app: mariadb
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath: 
    path: /data/mariadb-pv/ 