---
apiVersion: v1
kind: Service
metadata:
  name: nexus
spec:
  type: ClusterIP
  selector:
    app: nexus
  ports:
  - name: http
    port: 80
    targetPort: 8081
  - name: docker
    port:  8123
--- 
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nexus
spec:
  serviceName: 'nexus'
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      containers:
      - name: nexus
        image: feldmannjr/nexus3:latest
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "2Gi"
            cpu: "1"
        env:
          - name: NEXUS_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: nexus-secrets
                key: admin-password
          - name: NEXUS_DEPLOYER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: nexus-secrets
                key: deployer-password
        ports:
          - name: http-port
            containerPort: 8081
          - name: docker-port
            containerPort: 8123
        volumeMounts:
          - mountPath: /nexus-data
            name: nexus-storage
          - mountPath: /etc/nexus-init.d/
            name: initialize-volume
      volumes:
        - name: initialize-volume
          configMap:
              name: 'nexus-initialize-scripts-config'
  volumeClaimTemplates:
  - metadata:
      name: nexus-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

--- 
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nexus-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 1g
spec:
  rules:
    - host: nexus.minikube
      http:
        paths:
          - backend:
              serviceName: nexus       
              servicePort: http
            path: /
    - host: docker.nexus.minikube
      http:
        paths:
            - backend:
                serviceName: nexus       
                servicePort: docker
              path: /